framework:
    messenger:
        failure_transport: failed
        transports:
            async:
                dsn: doctrine://default
                retry_strategy:
                    max_retries: 3
                    delay: 1000
                    multiplier: 2
                    max_delay: 0
            failed: doctrine://default?queue_name=failed

        routing:
            App\Event\Message\MessageCreated: async
            App\Event\Room\RoomUpdated: async
