security:
  encoders:
    App\Entity\User:
      algorithm: auto
  providers:
    users:
      entity:
        class: App\Entity\User
        property: username
  firewalls:
    dev:
      pattern: ^/(_(profiler|wdt)|css|images|js)/
      security: false
    login:
      pattern:  ^/api/login
      stateless: true
      anonymous: true
      json_login:
        check_path: /api/login_check
        success_handler: lexik_jwt_authentication.handler.authentication_success
        failure_handler: lexik_jwt_authentication.handler.authentication_failure
    api_public:
      pattern: ^/api$
      stateless: true
      security: false
      anonymous: true
    api:
      pattern: ^/api
      stateless: true
      security: true
      anonymous: true
      guard:
        authenticators:
          - lexik_jwt_authentication.jwt_token_authenticator
  access_control:
    - { path: ^/api/users/registration, roles: IS_AUTHENTICATED_ANONYMOUSLY }
    - { path: ^/api/login_check, roles: IS_AUTHENTICATED_ANONYMOUSLY }
    - { path: ^/api, roles: IS_AUTHENTICATED_ANONYMOUSLY }
    - { path: ^/api/, roles: ROLE_USER }
