parameters:

services:
    _defaults:
        autowire: true
        autoconfigure: true
    App\:
        resource: '../src/*'
        exclude: '../src/{DependencyInjection,Actions,Entity,Migrations,Tests,Kernel.php}'

    App\Actions\:
        resource: '../src/Actions/*'
